# Generated by Django 3.1.3 on 2021-03-27 13:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemporalGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_name', models.TextField(default='Room_535', max_length=1024)),
                ('player_x', models.TextField(default='Groundhog_414', max_length=1024)),
                ('player_y', models.TextField(default='RoyalEagle_185', max_length=1024)),
            ],
        ),
    ]
