# Generated by Django 3.1.3 on 2021-03-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporalgame',
            name='player_x',
            field=models.TextField(default='Groundhog_761', max_length=1024),
        ),
        migrations.AlterField(
            model_name='temporalgame',
            name='player_y',
            field=models.TextField(default='RoyalEagle_486', max_length=1024),
        ),
        migrations.AlterField(
            model_name='temporalgame',
            name='room_name',
            field=models.TextField(max_length=1024),
        ),
    ]
