# Generated by Django 3.1.3 on 2021-03-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210327_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporalgame',
            name='player_x',
            field=models.TextField(default='Groundhog_654', max_length=1024),
        ),
        migrations.AlterField(
            model_name='temporalgame',
            name='player_y',
            field=models.TextField(max_length=1024, null=True),
        ),
    ]
