# Generated by Django 3.1.3 on 2021-03-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210327_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporalgame',
            name='player_x',
            field=models.TextField(max_length=1024, null=True),
        ),
    ]
