# Generated by Django 3.1.3 on 2021-03-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20210327_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporalgame',
            name='columns',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='temporalgame',
            name='rows',
            field=models.IntegerField(default=3),
        ),
    ]
